name: Build and Upload

on:
  push:
    branches:
      - release
    tags:
      - 'v*.*.*'

jobs:
  build-macos:
    runs-on: macos-12

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21

      - name: Set up Node 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Set up Wails
        run: |
          go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Build and Package
        run: |
          npm install
          npm run build:macos

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dailies-tracker.app
          path: packages/app/bin/dailies-tracker.app

  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21

      - name: Set up Node 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Set up Wails
        run: |
          go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Build and Package
        run: |
          npm install
          npm run build:windows

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: 'Dailies Tracker.exe'
          path: 'packages/app/bin/Dailies Tracker.exe'

  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21

      - name: Set up Node 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Set up Wails
        run: |
          go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Setup dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev

      - name: Build and Package
        run: |
          npm install
          npm run build:linux

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dailies-tracker
          path: packages/app/bin/dailies-tracker
